#!/bin/bash

export ROOT_DIR="/opt"
export BOT_DIR="/botdata"

# Paths
export TINODE_BASE_DIR="${ROOT_DIR}/tinode"
export TINODE_SCRIPT_DIR="${TINODE_BASE_DIR}/scripts"
export TINODE_TPL_CONFIG="${TINODE_BASE_DIR}/tinode.conf.tpl"
export TINODE_MAIN_CONFIG="${TINODE_BASE_DIR}/tinode.conf"
export TINODE_EXE_FILE="${TINODE_BASE_DIR}/tinode"

export TINODE_DEFAULT_EXTERNAL_CONFIG=""
export TINODE_DEFAULT_EXTERNAL_STATIC_DIR="${TINODE_BASE_DIR}/static"
export TINODE_EXTERNAL_CONFIG="${TINODE_EXTERNAL_CONFIG:-$TINODE_DEFAULT_EXTERNAL_CONFIG}"
export TINODE_STATIC_DIR="${TINODE_STATIC_DIR:-$TINODE_DEFAULT_EXTERNAL_STATIC_DIR}"

# FLAGS
export TINODE_DEFAULT_RESET_DB="false"
export TINODE_DEFAULT_UPGRADE_DB="false"
export TINODE_DEFAULT_SAMPLE_DATA="${TINODE_BASE_DIR}/data/data.json"
export TINODE_DEFAULT_NO_DB_INIT="false"
# ---
export TINODE_RESET_DB="${TINODE_RESET_DB:-$TINODE_DEFAULT_RESET_DB}"
export TINODE_UPGRADE_DB="${TINODE_UPGRADE_DB:-$TINODE_DEFAULT_UPGRADE_DB}"
export TINODE_SAMPLE_DATA="${TINODE_SAMPLE_DATA:-$TINODE_DEFAULT_SAMPLE_DATA}"
export TINODE_NO_DB_INIT="${TINODE_NO_DB_INIT:-$TINODE_DEFAULT_NO_DB_INIT}"


# Default constants
export TINODE_DEFAULT_BIND_ADDRESS="0.0.0.0"
export TINODE_DEFAULT_BIND_PORT="6060"
export TINODE_DEFAULT_API_PATH="/"
export TINODE_DEFAULT_CACHE_CONTROL="39600"
export TINODE_DEFAULT_STATIC_MOUNT="/"
export TINODE_DEFAULT_BIND_GRPC_ADDRESS="0.0.0.0"
export TINODE_DEFAULT_BIND_GRPC_PORT="16060"
export TINODE_DEFAULT_GRPC_KEEPALIVE_ENABLED="true"
export TINODE_DEFAULT_API_KEY_SALT="T713/rYYgW7g4m3vG6zGRh7+FM1t0T8j13koXScOAj4="
export TINODE_DEFAULT_MAX_MESSAGE_SIZE="262144"
export TINODE_DEFAULT_MAX_SUBSCRIBER_COUNT="128"
export TINODE_DEFAULT_MAX_TAG_COUNT="16"
export TINODE_DEFAULT_EXPVAR="/debug/vars"
export TINODE_DEFAULT_SERVER_STATUS="/debug/status"
export TINODE_DEFAULT_USE_X_FORWARDED_FOR="true"
export TINODE_DEFAULT_COUNTRY_CODE="US"
export TINODE_DEFAULT_USE_ADAPTER=""
# ---
export TINODE_API_PATH="${TINODE_API_PATH:-$TINODE_DEFAULT_API_PATH}"
export TINODE_CACHE_CONTROL="${TINODE_CACHE_CONTROL:-$TINODE_DEFAULT_CACHE_CONTROL}"
export TINODE_STATIC_MOUNT="${TINODE_STATIC_MOUNT:-$TINODE_DEFAULT_STATIC_MOUNT}"
export TINODE_BIND_GRPC_ADDRESS="${TINODE_BIND_GRPC_ADDRESS:-$TINODE_DEFAULT_BIND_GRPC_ADDRESS}"
export TINODE_BIND_GRPC_PORT="${TINODE_BIND_GRPC_PORT:-$TINODE_DEFAULT_BIND_GRPC_PORT}"
export TINODE_API_KEY_SALT="${TINODE_API_KEY_SALT:-$TINODE_DEFAULT_API_KEY_SALT}"
export TINODE_MAX_MESSAGE_SIZE="${TINODE_MAX_MESSAGE_SIZE:-$TINODE_DEFAULT_MAX_MESSAGE_SIZE}"
export TINODE_MAX_SUBSCRIBER_COUNT="${TINODE_MAX_SUBSCRIBER_COUNT:-$TINODE_DEFAULT_MAX_SUBSCRIBER_COUNT}"
export TINODE_MAX_TAG_COUNT="${TINODE_MAX_TAG_COUNT:-$TINODE_DEFAULT_MAX_TAG_COUNT}"
export TINODE_EXPVAR="${TINODE_EXPVAR:-$TINODE_DEFAULT_EXPVAR}"
export TINODE_SERVER_STATUS="${TINODE_SERVER_STATUS:-$TINODE_DEFAULT_SERVER_STATUS}"
export TINODE_USE_X_FORWARDED_FOR=${TINODE_USE_X_FORWARDED_FOR:-$TINODE_DEFAULT_USE_X_FORWARDED_FOR}
export TINODE_COUNTRY_CODE=${TINODE_COUNTRY_CODE:-$TINODE_DEFAULT_COUNTRY_CODE}
# Application socket
export TINODE_BIND_ADDRESS="${TINODE_BIND_ADDRESS:-$TINODE_DEFAULT_BIND_ADDRESS}"
export TINODE_BIND_PORT="${TINODE_BIND_PORT:-$TINODE_DEFAULT_BIND_PORT}"
export TINODE_DEFAULT_BIND_SOCKET="${TINODE_BIND_ADDRESS}:${TINODE_BIND_PORT}"
export TINODE_BIND_SOCKET="${TINODE_BIND_SOCKET:-$TINODE_DEFAULT_BIND_SOCKET}"
# Application GRPC socket
export TINODE_BIND_GRPC_ADDRESS="${TINODE_BIND_GRPC_ADDRESS:-$TINODE_DEFAULT_BIND_GRPC_ADDRESS}"
export TINODE_BIND_GRPC_PORT="${TINODE_BIND_GRPC_PORT:-$TINODE_DEFAULT_BIND_GRPC_PORT}"
export TINODE_DEFAULT_BIND_GRPC_SOCKET="${TINODE_BIND_GRPC_ADDRESS}:${TINODE_BIND_GRPC_PORT}"
export TINODE_BIND_GRPC_SOCKET="${TINODE_BIND_GRPC_SOCKET:-$TINODE_DEFAULT_BIND_GRPC_SOCKET}"
export TINODE_GRPC_KEEPALIVE_ENABLED="${TINODE_GRPC_KEEPALIVE_ENABLED:-$TINODE_DEFAULT_GRPC_KEEPALIVE_ENABLED}"

# TLS defaults
export TINODE_DEFAULT_TLS_ENABLED="false"
export TINODE_DEFAULT_TLS_HTTP_REDIRECT=":80"
export TINODE_DEFAULT_TLS_CERT_FILE="/etc/ssl/certs/your.domain.crt"
export TINODE_DEFAULT_TLS_KEY_FILE="/etc/ssl/private/your.domain.key"
export TINODE_DEFAULT_TLS_DOMAIN_NAME=""
export TINODE_DEFAULT_TLS_CONTACT_ADDRESS=""
# ---
export TINODE_TLS_ENABLED="${TINODE_TLS_ENABLED:-$TINODE_DEFAULT_TLS_ENABLED}"
export TINODE_TLS_HTTP_REDIRECT="${TINODE_TLS_HTTP_REDIRECT:-$TINODE_DEFAULT_TLS_HTTP_REDIRECT}"
export TINODE_TLS_CERT_FILE="${TINODE_TLS_CERT_FILE:-$TINODE_DEFAULT_TLS_CERT_FILE}"
export TINODE_TLS_KEY_FILE="${TINODE_TLS_KEY_FILE:-$TINODE_DEFAULT_TLS_KEY_FILE}"
export TINODE_TLS_DOMAIN_NAME="${TINODE_TLS_DOMAIN_NAME:-$TINODE_DEFAULT_TLS_DOMAIN_NAME}"
export TINODE_TLS_CONTACT_ADDRESS="${TINODE_TLS_CONTACT_ADDRESS:-$TINODE_DEFAULT_TLS_CONTACT_ADDRESS}"

# Auth basic (login + password)
export TINODE_DEFAULT_BASIC_AUTH_ADD_TO_TAGS="true"
export TINODE_DEFAULT_BASIC_AUTH_MIN_LOGIN_LENGTH="4"
export TINODE_DEFAULT_BASIC_AUTH_MIN_PASSWORD_LENGTH="6"
# ---
export TINODE_BASIC_AUTH_ADD_TO_TAGS="${TINODE_BASIC_AUTH_ADD_TO_TAGS:-$TINODE_DEFAULT_BASIC_AUTH_ADD_TO_TAGS}"
export TINODE_BASIC_AUTH_MIN_LOGIN_LENGTH="${TINODE_BASIC_AUTH_MIN_LOGIN_LENGTH:-$TINODE_DEFAULT_BASIC_AUTH_MIN_LOGIN_LENGTH}"
export TINODE_BASIC_AUTH_MIN_PASSWORD_LENGTH="${TINODE_BASIC_AUTH_MIN_PASSWORD_LENGTH:-$TINODE_DEFAULT_BASIC_AUTH_MIN_PASSWORD_LENGTH}"

# Auth token
export TINODE_DEFAULT_TOKEN_AUTH_EXPIRE_IN="1209600"
export TINODE_DEFAULT_TOKEN_AUTH_SERIAL_NUM="1"
export TINODE_DEFAULT_TOKEN_AUTH_KEY="wfaY2RgF2S1OQI/ZlK+LSrp1KB2jwAdGAIHQ7JZn+Kc="
# ---
export TINODE_TOKEN_AUTH_EXPIRE_IN="${TINODE_TOKEN_AUTH_EXPIRE_IN:-$TINODE_DEFAULT_TOKEN_AUTH_EXPIRE_IN}"
export TINODE_TOKEN_AUTH_SERIAL_NUM="${TINODE_TOKEN_AUTH_SERIAL_NUM:-$TINODE_DEFAULT_TOKEN_AUTH_SERIAL_NUM}"
export TINODE_TOKEN_AUTH_KEY="${TINODE_TOKEN_AUTH_KEY:-$TINODE_DEFAULT_TOKEN_AUTH_KEY}"

# Use adapter
export TINODE_USE_ADAPTER="${TINODE_USE_ADAPTER:-$TINODE_DEFAULT_USE_ADAPTER}"

# Mongodb store
export TINODE_DEFAULT_MONGODB_URI=""
export TINODE_DEFAULT_MONGODB_ADDRESSES=""
export TINODE_DEFAULT_MONGODB_DATABASE=""
export TINODE_DEFAULT_MONGODB_REPLICA_SET=""
export TINODE_DEFAULT_MONGODB_AUTH_MECHANISM=""
export TINODE_DEFAULT_MONGODB_AUTH_SOURCE=""
export TINODE_DEFAULT_MONGODB_USERNAME=""
export TINODE_DEFAULT_MONGODB_PASSWORD=""
export TINODE_DEFAULT_MONGODB_TLS="true"
export TINODE_DEFAULT_MONGODB_TLS_CERT_FILE=""
export TINODE_DEFAULT_MONGODB_TLS_PRIVATE_KEY=""
export TINODE_DEFAULT_MONGODB_TLS_SKIP_VERIFY="false"
# ---
export TINODE_MONGODB_URI="${TINODE_MONGODB_URI:-$TINODE_DEFAULT_MONGODB_URI}"
export TINODE_MONGODB_ADDRESSES="${TINODE_MONGODB_ADDRESSES:-$TINODE_DEFAULT_MONGODB_ADDRESSES}"
export TINODE_MONGODB_DATABASE="${TINODE_MONGODB_DATABASE:-$TINODE_DEFAULT_MONGODB_DATABASE}"
export TINODE_MONGODB_REPLICA_SET="${TINODE_MONGODB_REPLICA_SET:-$TINODE_DEFAULT_MONGODB_REPLICA_SET}"
export TINODE_MONGODB_AUTH_MECHANISM="${TINODE_MONGODB_AUTH_MECHANISM:-$TINODE_DEFAULT_MONGODB_AUTH_MECHANISM}"
export TINODE_MONGODB_AUTH_SOURCE="${TINODE_MONGODB_AUTH_SOURCE:-$TINODE_DEFAULT_MONGODB_AUTH_SOURCE}"
export TINODE_MONGODB_USERNAME="${TINODE_MONGODB_USERNAME:-$TINODE_DEFAULT_MONGODB_USERNAME}"
export TINODE_MONGODB_PASSWORD="${TINODE_MONGODB_PASSWORD:-$TINODE_DEFAULT_MONGODB_PASSWORD}"
export TINODE_MONGODB_TLS="${TINODE_MONGODB_TLS:-$TINODE_DEFAULT_MONGODB_TLS}"
export TINODE_MONGODB_TLS_CERT_FILE="${TINODE_MONGODB_TLS_CERT_FILE:-$TINODE_DEFAULT_MONGODB_TLS_CERT_FILE}"
export TINODE_MONGODB_TLS_PRIVATE_KEY="${TINODE_MONGODB_TLS_PRIVATE_KEY:-$TINODE_DEFAULT_MONGODB_TLS_PRIVATE_KEY}"
export TINODE_MONGODB_TLS_SKIP_VERIFY="${TINODE_MONGODB_TLS_SKIP_VERIFY:-$TINODE_DEFAULT_MONGODB_TLS_SKIP_VERIFY}"

# Email config
export TINODE_DEFAULT_EMAIL_VALIDATION=''
export TINODE_DEFAULT_SMTP_HOST_URL="http://localhost:6060/"
export TINODE_DEFAULT_SMTP_SERVER="smtp.example.com"
export TINODE_DEFAULT_SMTP_PORT="25"
export TINODE_DEFAULT_SMTP_LOGIN=""
export TINODE_DEFAULT_SMTP_SENDER="Tinode <noreply@example.com>"
export TINODE_DEFAULT_SMTP_SENDER_PASSWORD=""
export TINODE_DEFAULT_SMTP_AUTH_MECHANISM="plain"
export TINODE_DEFAULT_SMTP_INSECURE_SKIP_VERIFY="false"
export TINODE_DEFAULT_SMTP_LANGUAGES='"en","ru"'
export TINODE_DEFAULT_SMTP_MAX_RETRIES="3"
export TINODE_DEFAULT_SMTP_DOMAINS=""
export TINODE_DEFAULT_SMTP_DEBUG_RESPONSE=""
# ---
export TINODE_EMAIL_VALIDATION="${TINODE_EMAIL_VALIDATION:-$TINODE_DEFAULT_EMAIL_VALIDATION}"
export TINODE_SMTP_HOST_URL="${TINODE_SMTP_HOST_URL:-$TINODE_DEFAULT_SMTP_HOST_URL}"
export TINODE_SMTP_SERVER="${TINODE_SMTP_SERVER:-$TINODE_DEFAULT_SMTP_SERVER}"
export TINODE_SMTP_PORT="${TINODE_SMTP_PORT:-$TINODE_DEFAULT_SMTP_PORT}"
export TINODE_SMTP_LOGIN="${TINODE_SMTP_LOGIN:-$TINODE_DEFAULT_SMTP_LOGIN}"
export TINODE_SMTP_SENDER="${TINODE_SMTP_SENDER:-$TINODE_DEFAULT_SMTP_SENDER}"
export TINODE_SMTP_SENDER_PASSWORD="${TINODE_SMTP_SENDER_PASSWORD:-$TINODE_DEFAULT_SMTP_SENDER_PASSWORD}"
export TINODE_SMTP_AUTH_MECHANISM="${TINODE_SMTP_AUTH_MECHANISM:-$TINODE_DEFAULT_SMTP_AUTH_MECHANISM}"
export TINODE_SMTP_INSECURE_SKIP_VERIFY="${TINODE_SMTP_INSECURE_SKIP_VERIFY:-$TINODE_DEFAULT_SMTP_INSECURE_SKIP_VERIFY}"
export TINODE_SMTP_LANGUAGES="${TINODE_SMTP_LANGUAGES:-$TINODE_DEFAULT_SMTP_LANGUAGES}"
export TINODE_SMTP_MAX_RETRIES="${TINODE_SMTP_MAX_RETRIES:-$TINODE_DEFAULT_SMTP_MAX_RETRIES}"
export TINODE_SMTP_DOMAINS="${TINODE_SMTP_DOMAINS:-$TINODE_DEFAULT_SMTP_DOMAINS}"
export TINODE_SMTP_DEBUG_RESPONSE="${TINODE_SMTP_DEBUG_RESPONSE:-$TINODE_DEFAULT_SMTP_DEBUG_RESPONSE}"

